services:

  enrolments-webapp:
    restart: always
    build:
      context: ./enrolments
      dockerfile: Dockerfile-dev
    depends_on:
      mysql-enrolments:
        condition: service_healthy
    volumes:
      - ./enrolments:/app
    networks:
      - dk-network

  courses-webapp:
    restart: always
    build:
      context: ./courses
      dockerfile: Dockerfile-dev
    depends_on:
      mysql-courses:
        condition: service_healthy
    volumes:
      - ./courses:/app
    networks:
      - dk-network

  users-webapp:
    restart: always
    build:
      context: ./users
      dockerfile: Dockerfile-dev
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./users:/app
    networks:
      - dk-network

  api-gateway-webapp:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile-dev
    volumes:
      - ./api-gateway:/app
    networks:
      - dk-network


  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - users-webapp
      - courses-webapp
      - enrolments-webapp
      - api-gateway-webapp
    networks:
      - dk-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
      - mongo:/data/db
    healthcheck:
      test: >
        mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - dk-network

  mysql-enrolments:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-enrolments:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_ENROLMENT_DATABASE}
      MYSQL_USER: ${MYSQL_ENROLMENT_USER}
      MYSQL_PASSWORD: ${MYSQL_ENROLMENT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ENROLMENT_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_ENROLMENT_PORT}
      TZ: Europe/Warsaw
    ports:
      - 3308:3308
    expose:
      - 3308
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - dk-network

  mysql-courses:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-courses:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      TZ: Europe/Warsaw
    ports:
      - 3307:3307
    expose:
      - 3307
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - dk-network

networks:
  dk-network:

volumes:
  mysql-enrolments:
  mysql-courses:
  mongo:

