services:

  users-webapp:
    restart: always
    build:
      context: ./users
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./users:/app
    networks:
      - dk-network

  api-gateway-webapp:
    restart: always
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - ./users:/app
    networks:
      - dk-network


  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - users-webapp
    networks:
      - dk-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
      - mongo:/data/db
    healthcheck:
      test: >
        mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - dk-network

networks:
  dk-network:

volumes:
  mongo:

